#!/usr/bin/env python3
"""gen_skills2.py — the rest of the skill library (called by gen_skills.py).

Frameworks, databases, devops, testing, engineering practices, data/ML, mobile,
web, systems/CLI, networking, algorithms, architecture, game dev, and a second
wave of security. Content is compact but real: when to use, a concrete checklist,
the pitfalls that bite.
"""
from __future__ import annotations


def generate(skill, slug):
    S = skill

    # ── web frameworks ──
    fw = "frameworks"
    S(fw, "React components & state", "Build correct React components with clean state and effects.",
      ["react", "frontend", "hooks"], "Building or fixing a React UI.",
      ["Keep components small and pure; lift state only as high as needed.",
       "Effects for synchronization only; list every dependency; clean up subscriptions.",
       "Key lists by stable ids, never index; memoize only measured hot renders.",
       "Derive state, don't duplicate it."],
      ["Missing effect deps cause stale closures.",
       "Index keys corrupt lists on reorder.",
       "Overusing useMemo/useCallback adds noise and bugs."])
    S(fw, "Vue components", "Build Vue 3 components with the Composition API correctly.",
      ["vue", "frontend"], "Building or fixing a Vue app.",
      ["Use `<script setup>` + composition API; ref/reactive appropriately.",
       "Computed for derived state; watchers only for side effects.",
       "Props down, events up; avoid mutating props."],
      ["Losing reactivity by destructuring reactive objects.",
       "Mutating props instead of emitting."])
    S(fw, "Django", "Build secure, idiomatic Django apps.",
      ["django", "python", "backend"], "Building or reviewing a Django project.",
      ["Use the ORM with parameterized queries; migrations for schema.",
       "Keep views thin, logic in models/services; use forms/serializers for validation.",
       "CSRF middleware on; never disable it for convenience; use `select_related`/`prefetch_related`.",
       "Secrets in env; DEBUG=False in prod; ALLOWED_HOSTS set."],
      ["`.raw()`/`.extra()` reintroduce SQLi.",
       "N+1 queries from lazy relations.",
       "DEBUG=True in prod leaks everything."])
    S(fw, "Flask", "Build small, secure Flask services.",
      ["flask", "python", "backend"], "Building a Flask app or API.",
      ["Use blueprints; validate input; parameterize DB access.",
       "Set a strong SECRET_KEY from env; secure session cookies.",
       "Handle errors with error handlers, not bare try/except everywhere."],
      ["Debug mode on in prod exposes the Werkzeug console (RCE).",
       "Rendering user input in templates → SSTI."])
    S(fw, "FastAPI", "Build typed, validated FastAPI services.",
      ["fastapi", "python", "async", "backend"], "Building an async Python API.",
      ["Pydantic models for request/response validation; dependency injection for auth/db.",
       "Async endpoints for I/O; don't block the loop.",
       "Return explicit response models; document with the auto OpenAPI."],
      ["Blocking calls in async endpoints stall the server.",
       "Leaking internal models as responses over-exposes data."])
    S(fw, "Express (Node)", "Build secure Express APIs.",
      ["express", "node", "backend"], "Building a Node/Express service.",
      ["Validate input (zod/joi); use helmet; parameterize queries.",
       "Centralized error middleware; async handlers wrapped to catch rejections.",
       "Rate-limit and set CORS deliberately."],
      ["Unhandled promise rejections crash the process.",
       "Trusting req.body shape leads to mass-assignment."])
    for f, t in [("Svelte", "svelte"), ("Angular", "angular"), ("Next.js", "nextjs"),
                 ("Rails", "rails"), ("Spring Boot", "spring"), ("Laravel", "laravel")]:
        S(fw, f, f"Build idiomatic {f} apps with its conventions and security defaults.",
          [t, "framework"], f"Building or reviewing a {f} project.",
          [f"Follow {f}'s project structure and conventions.",
           "Validate all input; keep secrets in env; parameterize data access.",
           "Use the framework's auth/session/CSRF features rather than rolling your own.",
           "Write tests with the framework's standard tooling."],
          ["Fighting the framework's conventions creates unmaintainable code.",
           "Disabling built-in security features for convenience."])

    # ── databases ──
    db = "databases"
    S(db, "PostgreSQL", "Use Postgres well — schema, queries, and features.",
      ["postgres", "sql", "database"], "Designing or querying a Postgres DB.",
      ["Right types (jsonb, arrays, timestamptz); constraints enforce invariants.",
       "Parameterized queries only; use EXPLAIN ANALYZE to tune.",
       "Index for your query patterns; partial/expression indexes when apt.",
       "Transactions with the right isolation level."],
      ["Missing indexes on FK/filter columns cause seq scans.",
       "Storing timestamps without timezone.",
       "SELECT * in hot paths."])
    S(db, "SQL indexing", "Add the right indexes to make queries fast.",
      ["sql", "indexing", "performance", "database"], "A slow query or a table that will grow.",
      ["Read the query plan; find the seq scan / sort / nested loop hurting you.",
       "Index columns used in WHERE/JOIN/ORDER BY; composite index column order matters (equality then range).",
       "Covering indexes to avoid table lookups; partial indexes for skewed data.",
       "Re-check the plan after adding — confirm it's used."],
      ["Too many indexes slow writes and waste space.",
       "Wrong composite order = index unused.",
       "Functions on indexed columns disable the index."])
    S(db, "Database migrations", "Write safe, reversible schema migrations.",
      ["migrations", "database", "schema"], "Changing a production schema.",
      ["Make migrations reversible; test up AND down.",
       "For big tables: add columns nullable, backfill in batches, then add constraints — avoid long locks.",
       "Deploy schema changes backward-compatible with the running code (expand/contract).",
       "Never edit an applied migration; add a new one."],
      ["Adding a NOT NULL column with a default rewrites/locks big tables (DB-dependent).",
       "Dropping a column the old code still uses breaks during rollout."])
    for d, t in [("MySQL", "mysql"), ("SQLite", "sqlite"), ("MongoDB", "mongodb"),
                 ("Redis", "redis")]:
        S(db, d, f"Use {d} correctly for its strengths.",
          [t, "database"], f"Working with {d}.",
          [f"Model data for {d}'s access patterns, not a generic schema.",
           "Parameterize/validate all input; set resource limits and timeouts.",
           "Index/shape data for your reads; plan backups and eviction/retention."],
          ["Using it as the wrong kind of store for the workload.",
           "No backups / no eviction policy."])
    S(db, "Transactions & isolation", "Use DB transactions and isolation levels correctly.",
      ["transactions", "acid", "database"], "Multi-step writes that must be consistent.",
      ["Wrap related writes in one transaction; keep them short.",
       "Pick isolation for the anomaly you must prevent (lost update, phantom).",
       "Handle serialization failures with retries; avoid holding locks over network calls."],
      ["Long transactions block others and bloat MVCC.",
       "Assuming default isolation prevents all anomalies."])
    S(db, "Preventing N+1 queries", "Find and kill N+1 query patterns.",
      ["performance", "orm", "database"], "An endpoint issuing many small queries.",
      ["Log/inspect query count per request; find the loop issuing per-row queries.",
       "Batch with a join / IN clause / eager loading (select_related, includes).",
       "Cache read-heavy lookups when correct to do so."],
      ["ORMs hide N+1 behind lazy attributes.",
       "Eager-loading everything over-fetches — load what you use."])

    # ── devops ──
    do = "devops"
    S(do, "Docker images", "Write small, secure, reproducible Docker images.",
      ["docker", "containers"], "Containerizing an app.",
      ["Multi-stage builds; slim/distroless base; pin base tags by digest.",
       "Run as non-root; copy only what's needed; leverage layer caching (deps before code).",
       "No secrets in layers or ENV baked into the image; use build args/secrets mounts.",
       "One process per container; healthcheck."],
      ["`latest` base tags break reproducibility.",
       "Secrets baked into layers persist in history.",
       "Running as root is an easy container escape amplifier."])
    S(do, "Kubernetes basics", "Deploy and operate workloads on Kubernetes safely.",
      ["kubernetes", "k8s", "containers"], "Deploying to a k8s cluster.",
      ["Set resource requests/limits, liveness/readiness probes.",
       "Least-privilege: non-root, read-only FS, drop caps, network policies.",
       "Config in ConfigMaps, secrets in Secrets (or a manager); never in images.",
       "Use rolling updates with proper readiness to avoid downtime."],
      ["No limits → noisy-neighbor and OOM kills.",
       "Secrets in env/plain manifests leak.",
       "No readiness probe → traffic to a not-ready pod."])
    S(do, "CI/CD pipelines", "Build reliable, secure CI/CD pipelines.",
      ["ci-cd", "automation"], "Setting up build/test/deploy automation.",
      ["Fast feedback: lint+test on every PR; cache deps; fail fast.",
       "Pin action/tool versions; least-privilege tokens; scan deps and secrets in CI.",
       "Separate build from deploy; require green + review before deploy; make deploys reproducible.",
       "Store artifacts; enable rollback."],
      ["Long-lived broad tokens in CI are a breach multiplier.",
       "Flaky tests that get ignored erode the whole pipeline."])
    S(do, "GitHub Actions", "Write secure, efficient GitHub Actions workflows.",
      ["github-actions", "ci-cd"], "Automating on GitHub.",
      ["Pin actions to a commit SHA; minimal `permissions:`; use OIDC over static secrets.",
       "Cache dependencies; matrix builds; concurrency to cancel superseded runs.",
       "Never `pull_request_target` with untrusted checkout + secrets."],
      ["`@v3` tags can move; pin SHAs for third-party actions.",
       "`pull_request_target` + checkout of PR code + secrets = RCE by contributors."])
    for tool, t in [("Terraform", "terraform"), ("Ansible", "ansible"),
                    ("nginx", "nginx"), ("systemd services", "systemd")]:
        S(do, tool, f"Use {tool} correctly for reproducible, secure infra/config.",
          [t, "infra"], f"Working with {tool}.",
          [f"Keep {tool} config declarative, version-controlled, and reviewed.",
           "Least privilege; secrets from a manager, never in plaintext config.",
           "Test changes in a safe environment; make them idempotent/reversible."],
          ["Manual drift from the declared state.",
           "Secrets committed in plaintext."])
    S(do, "Monitoring & alerting", "Instrument a service so you know when it breaks.",
      ["monitoring", "observability", "sre"], "Operating a service in production.",
      ["Emit the four golden signals: latency, traffic, errors, saturation.",
       "Alert on symptoms users feel (SLO burn), not every blip; make alerts actionable.",
       "Dashboards for triage; structured logs correlated by request id."],
      ["Alert fatigue from noisy, non-actionable alerts.",
       "Logging without correlation ids makes tracing impossible."])
    S(do, "Secrets management", "Handle secrets safely across dev and prod.",
      ["secrets", "security", "devops"], "Any secret (keys, tokens, DB creds).",
      ["Store in a secret manager / env, never in code or images.",
       "Least-privilege scoping; rotate regularly and on suspected exposure.",
       "Separate secrets per environment; audit access."],
      ["Secrets in git history persist after deletion — rotate.",
       "One shared god-credential everywhere."])

    # ── testing ──
    te = "testing"
    S(te, "Unit testing", "Write focused, fast unit tests.",
      ["unit", "testing"], "Testing a single unit of logic.",
      ["One behavior per test; arrange-act-assert; descriptive names.",
       "Cover happy path, edges, and error paths; deterministic, no I/O.",
       "Add a failing test first when fixing a bug (it should fail, then pass)."],
      ["Testing implementation details makes refactors painful.",
       "Hidden shared state between tests."])
    S(te, "Integration testing", "Test components working together.",
      ["integration", "testing"], "Verifying units integrate (DB, API, services).",
      ["Test real boundaries (a real test DB, a spun-up service) where it matters.",
       "Seed and tear down state; isolate tests; use containers/fixtures.",
       "Assert on observable behavior, not internals."],
      ["Shared mutable test DB causes order-dependent flakiness.",
       "Mocking the very boundary you're trying to verify."])
    S(te, "End-to-end testing", "Test the full user flow.",
      ["e2e", "testing", "playwright"], "Verifying critical user journeys.",
      ["Cover the few critical paths, not everything (E2E is slow/brittle).",
       "Use stable selectors (roles/test-ids); wait on conditions, not sleeps.",
       "Run against a known-seeded environment."],
      ["Fixed sleeps and CSS-selector coupling cause flakes.",
       "E2E-ing everything makes the suite unmaintainable."])
    S(te, "Mocking & test doubles", "Use mocks/stubs/fakes correctly.",
      ["mocking", "testing"], "Isolating code from slow/external dependencies.",
      ["Mock at architectural boundaries (network, clock, fs), not internal functions.",
       "Prefer fakes over deep mock expectations; verify behavior not call minutiae.",
       "Reset mocks between tests."],
      ["Over-mocking tests the mock, not your code.",
       "Mocking what you own instead of refactoring it."])
    S(te, "Property-based testing", "Find edge cases with generated inputs.",
      ["property-testing", "hypothesis", "fuzzing"], "Logic with a wide input space (parsers, encoders).",
      ["State invariants that must always hold; let the framework generate inputs (Hypothesis/fast-check).",
       "Use round-trip properties (decode(encode(x))==x); shrink failing cases.",
       "Add discovered failures as explicit regression tests."],
      ["Weak properties that always pass prove nothing.",
       "Nondeterministic properties without seeds."])
    S(te, "Test coverage", "Use coverage as a guide, not a target.",
      ["coverage", "testing"], "Deciding what still needs testing.",
      ["Measure branch coverage; look at what's uncovered and why.",
       "Prioritize risky/complex code over trivial getters.",
       "Coverage tells you what's untested, not that tested code is correct."],
      ["Chasing 100% leads to worthless tests.",
       "High coverage with weak assertions is false comfort."])
    S(te, "TDD", "Drive design with tests: red-green-refactor.",
      ["tdd", "testing"], "Building new logic where the design is uncertain.",
      ["Write a failing test for the next small behavior (red).",
       "Make it pass simply (green); then refactor with tests green.",
       "Repeat in small steps; let tests shape the interface."],
      ["Writing tests after defeats the design benefit.",
       "Big steps make failures hard to localize."])
    S(te, "Load & stress testing", "Find the capacity and breaking point of a service.",
      ["load-testing", "performance"], "Before a launch or capacity change.",
      ["Model realistic traffic; ramp up to find the knee and the breaking point.",
       "Measure p50/p95/p99 latency and error rate under load, not just averages.",
       "Test from close to prod; watch the whole stack (DB, queues) for the true bottleneck."],
      ["Averages hide tail latency — track percentiles.",
       "Testing the load tool's limits, not the service's."])

    # ── engineering practices ──
    pr = "practices"
    S(pr, "Git workflow", "Work effectively with git day to day.",
      ["git", "vcs"], "Any project under git.",
      ["Small, focused commits with clear messages; branch per change; rebase/merge per team norms.",
       "Pull/rebase before pushing; review diffs before committing (`git diff --staged`).",
       "Keep main green; use PRs for review."],
      ["Giant mixed commits are unreviewable and unrevertable.",
       "Committing secrets or generated files."])
    S(pr, "Git recovery", "Recover from git mistakes safely.",
      ["git", "recovery"], "You committed/reset/rebased wrong and need to fix it.",
      ["`git reflog` finds 'lost' commits; reset/cherry-pick back to them.",
       "Undo a bad commit with `git revert` (shared) or `reset` (local only).",
       "Recover deleted branches from reflog; stash rescues uncommitted work.",
       "Prefer non-destructive fixes on shared history."],
      ["`reset --hard` / force-push on shared branches destroys others' work.",
       "`push --force` over `--force-with-lease` clobbers teammates."])
    S(pr, "Code review", "Give and get useful code reviews.",
      ["code-review", "collaboration"], "Reviewing or submitting a change.",
      ["Review correctness and design first, style last (let a formatter handle style).",
       "Small PRs; explain the why; leave specific, kind, actionable comments.",
       "As author: self-review the diff first; keep PRs focused."],
      ["Nitpicking style while missing a real bug.",
       "Huge PRs get rubber-stamped."])
    S(pr, "Refactoring safely", "Improve code structure without changing behavior.",
      ["refactoring", "maintainability"], "Code that's hard to change but works.",
      ["Get tests green first; make small behavior-preserving steps; re-run tests each step.",
       "Rename for clarity, remove duplication, split big units, tighten interfaces.",
       "Never mix a refactor with a feature/bugfix in one commit."],
      ["Refactoring without tests is just rewriting and hoping.",
       "Big-bang rewrites lose behavior and history."])
    S(pr, "Debugging methodically", "Find root causes fast, without flailing.",
      ["debugging", "troubleshooting"], "Something is broken and you don't know why.",
      ["Reproduce reliably first; read the actual error/traceback.",
       "Form ONE hypothesis; bisect the space (git bisect, binary search, prints).",
       "Change one thing at a time; fix the root cause; add a regression test."],
      ["Shotgun-changing many things hides which fix worked.",
       "Fixing the symptom, not the cause."])
    S(pr, "Structured logging", "Log so future-you can debug production.",
      ["logging", "observability"], "Adding observability to a service.",
      ["Structured (key=value/JSON) with levels; include a request/correlation id.",
       "Log decisions and boundaries, not noise; never log secrets/PII.",
       "Make errors actionable: what failed, with what inputs, and the cause."],
      ["Logging secrets/PII is a breach.",
       "`print`-style logs without context are useless at 3am."])
    S(pr, "Error handling design", "Design where and how failures are handled.",
      ["errors", "design"], "Designing a module's failure behavior.",
      ["Decide per error: recover, retry, or propagate — don't silently swallow.",
       "Fail fast at boundaries; keep the core assuming valid data.",
       "Preserve context up the stack; give the caller enough to act."],
      ["Catch-all handlers that hide bugs.",
       "Returning sentinels that callers forget to check."])
    S(pr, "API design", "Design an interface others can use without reading the source.",
      ["api-design", "interfaces"], "Designing a public function/class/endpoint.",
      ["Make the common case easy and the API hard to misuse; consistent naming.",
       "Small surface; clear errors; document the contract and invariants.",
       "Version and keep backward compatibility for public APIs."],
      ["Leaking implementation details in the interface.",
       "Breaking changes without versioning."])
    S(pr, "Writing documentation", "Write docs people actually use.",
      ["documentation", "writing"], "Documenting a project or API.",
      ["Start with what it does and how to run it; then the gotchas.",
       "Show, don't just tell — runnable examples; keep docs next to code and current.",
       "Document the why for non-obvious decisions."],
      ["Docs that drift from the code mislead worse than none.",
       "Auto-generated docs with no examples."])
    S(pr, "Naming things", "Choose names that make code self-explaining.",
      ["naming", "readability"], "Any time you name a variable, function, or type.",
      ["Name by intent/role, not type or implementation; be consistent across the codebase.",
       "Length proportional to scope; avoid abbreviations and misleading names.",
       "Booleans read as predicates (is/has/can)."],
      ["Vague names (data, tmp, manager) hide meaning.",
       "A name that lies about what the thing does."])
    S(pr, "Commit messages", "Write commit messages that explain the change.",
      ["git", "commits"], "Every commit.",
      ["Imperative subject ≤50 chars; blank line; body explains WHY, not what.",
       "One logical change per commit; reference issues.",
       "Make history readable — future debuggers will `git blame` this."],
      ["'fix', 'wip', 'stuff' tell nobody anything.",
       "Bundling unrelated changes in one commit."])
    S(pr, "Semantic versioning", "Version releases so consumers know what changed.",
      ["semver", "releases"], "Publishing a library/API version.",
      ["MAJOR for breaking, MINOR for features, PATCH for fixes.",
       "Keep a changelog; deprecate before removing; document migrations.",
       "Don't break on a minor/patch."],
      ["Breaking changes in a patch release erode trust.",
       "0.x doesn't excuse silent breakage forever."])
    S(pr, "Managing technical debt", "Track and pay down debt deliberately.",
      ["tech-debt", "maintainability"], "A codebase accumulating shortcuts.",
      ["Make debt visible (TODOs with context, a debt list); tie paydown to nearby work.",
       "Fix the debt you keep tripping over; leave code better than you found it.",
       "Distinguish deliberate, tracked debt from accidental mess."],
      ["Invisible debt never gets paid.",
       "Big refactor-everything projects that never ship."])

    # ── data & ML ──
    da = "data-ml"
    S(da, "pandas", "Manipulate tabular data correctly and fast with pandas.",
      ["pandas", "python", "data"], "Analyzing/transforming tabular data in Python.",
      ["Vectorize — avoid iterrows/apply in hot paths; use built-in ops.",
       "Handle NaN and dtypes explicitly; avoid chained-assignment (use .loc).",
       "Merge/groupby correctly; check row counts after joins.",
       "Validate the shape/schema of inputs and outputs."],
      ["SettingWithCopy from chained indexing corrupts data silently.",
       "iterrows is orders of magnitude slower than vectorized ops."])
    S(da, "NumPy", "Use NumPy arrays efficiently and correctly.",
      ["numpy", "python", "data"], "Numerical array work in Python.",
      ["Vectorize with array ops/broadcasting; avoid Python loops over elements.",
       "Mind dtypes and overflow; understand views vs copies.",
       "Use the right axis; check shapes."],
      ["Integer overflow in fixed dtypes.",
       "Accidentally mutating a view of another array."])
    S(da, "Data cleaning", "Turn messy data into trustworthy data.",
      ["data-cleaning", "etl"], "Raw data before analysis or loading.",
      ["Profile first: nulls, dupes, types, ranges, outliers.",
       "Handle each deliberately (impute/drop/flag); document decisions.",
       "Validate against a schema; keep the raw copy; make cleaning reproducible."],
      ["Silent coercion (dates/numbers) corrupts data.",
       "Dropping rows without understanding why they're bad."])
    S(da, "ETL pipelines", "Build reliable, reproducible data pipelines.",
      ["etl", "data-engineering"], "Moving/transforming data between systems.",
      ["Make steps idempotent and re-runnable; checkpoint; validate at each stage.",
       "Handle late/duplicate/partial data; log row counts and rejects.",
       "Separate extract, transform, load; keep transforms testable."],
      ["Non-idempotent loads double data on retry.",
       "No validation → garbage propagates downstream."])
    S(da, "SQL analytics", "Answer analytical questions with SQL correctly.",
      ["sql", "analytics"], "Aggregating/reporting from a relational store.",
      ["Use window functions for running/ranked metrics; CTEs for readable steps.",
       "Mind NULL semantics in aggregates and joins; verify grain (one row per what?).",
       "Sanity-check totals against a known number."],
      ["JOINs that fan out rows inflate SUMs.",
       "NULLs silently dropped by aggregates/`NOT IN`."])
    S(da, "Model evaluation", "Evaluate ML models honestly.",
      ["ml", "evaluation"], "Assessing whether a model actually works.",
      ["Hold out a real test set; no leakage from train into features/preprocessing.",
       "Pick metrics that match the problem (not just accuracy on imbalanced data).",
       "Compare to a baseline; check per-slice performance and calibration."],
      ["Data leakage inflates offline metrics that collapse in prod.",
       "Accuracy on imbalanced data is misleading."])
    S(da, "Prompt engineering", "Get reliable results from an LLM in code.",
      ["llm", "prompting", "ai"], "Calling an LLM as part of a program.",
      ["Be specific: role, task, constraints, format; give examples.",
       "Constrain output (schema/JSON) and validate it; handle failures/retries.",
       "Keep context focused; test prompts against varied inputs."],
      ["Assuming the model follows format without validation.",
       "Stuffing irrelevant context degrades quality."])
    S(da, "RAG systems", "Build retrieval-augmented generation that stays grounded.",
      ["rag", "llm", "embeddings"], "Answering over a document/knowledge base with an LLM.",
      ["Chunk sensibly; embed; retrieve top-k with a real relevance threshold.",
       "Ground the answer in retrieved text; cite sources; refuse when nothing relevant.",
       "Evaluate retrieval quality separately from generation."],
      ["Retrieving irrelevant chunks → confident hallucination.",
       "No threshold → always answers even when it shouldn't."])

    # ── mobile (the operator builds these) ──
    mo = "mobile"
    S(mo, "Kivy Android apps", "Build single-file Kivy apps that package to Android.",
      ["kivy", "android", "python"], "Building a Python mobile app with Kivy.",
      ["Keep the UI in kv or built widgets; keep long work off the UI thread (Clock/threads).",
       "Request Android permissions at runtime; use plyer/pyjnius for platform APIs.",
       "Design for touch and small screens; test on device, not just desktop."],
      ["Blocking the main thread freezes the UI.",
       "Assuming desktop behavior matches Android."])
    S(mo, "Buildozer packaging", "Package a Python app to an APK with Buildozer.",
      ["buildozer", "android", "packaging"], "Turning a Kivy/Python app into an installable APK.",
      ["Declare requirements, permissions, and API levels in buildozer.spec.",
       "Match python-for-android recipes for native deps; clean builds when deps change.",
       "Test the release APK on a real device; sign it for distribution."],
      ["Missing a requirement/permission → runtime crash on device.",
       "Debug vs release signing confusion."])
    S(mo, "Android intents", "Use Android intents to integrate with other apps.",
      ["android", "intents"], "Launching another app/activity or sharing data.",
      ["Build explicit intents for a known target, implicit for an action; set data/extras/MIME.",
       "Verify a handler exists before launching; handle the no-handler case.",
       "Least-privilege on exported components you expose."],
      ["Assuming a target app is installed.",
       "Exporting components that leak IPC."])
    for m, t in [("React Native", "react-native"), ("Flutter", "flutter"),
                 ("iOS Swift", "swift"), ("App store release", "release")]:
        S(mo, m, f"Build/ship with {m} following its platform norms.",
          [t, "mobile"], f"Working with {m}.",
          [f"Follow {m} conventions for structure, navigation, and state.",
           "Handle permissions, lifecycle, and offline; keep the UI thread free.",
           "Test on real devices; follow store review/signing requirements."],
          ["Ignoring platform lifecycle/permission rules.",
           "Only testing on emulators/desktop."])

    # ── web (general) ──
    we = "web"
    web_topics = [
        ("REST API design", "rest", "Consistent resources, correct status codes, versioning, pagination, clear errors.",
         ["Model resources (nouns) with proper verbs and status codes.",
          "Paginate lists; version the API; return consistent error shapes.",
          "Idempotent PUT/DELETE; validate and authorize every request."],
         ["Verbs in URLs and 200-for-everything.", "Unbounded list endpoints."]),
        ("GraphQL", "graphql", "Design schemas and resolvers that are safe and performant.",
         ["Design the schema around client needs; resolve without N+1 (dataloaders).",
          "Limit query depth/complexity; authorize per field.",
          "Disable introspection in prod if sensitive."],
         ["Unbounded nested queries = DoS.", "Missing field-level authz."]),
        ("WebSockets", "websockets", "Build real-time features over WebSockets reliably.",
         ["Authenticate the handshake; validate every message; heartbeat/ping to detect dead peers.",
          "Handle reconnect with backoff; bound message size and rate.",
          "Clean up subscriptions on disconnect."],
         ["No auth on the socket after upgrade.", "No backpressure → memory blowup."]),
        ("HTTP caching", "caching", "Use HTTP caching correctly for speed and correctness.",
         ["Set Cache-Control/ETag/Last-Modified deliberately; validate with conditional requests.",
          "Cache static assets hard (immutable + hashed names); be careful with authenticated responses.",
          "Bust caches with versioned URLs."],
         ["Caching private/authed responses in shared caches.", "No cache busting → stale assets."]),
        ("CORS", "cors", "Configure CORS to allow what's needed and nothing more.",
         ["Allow specific origins, methods, headers — not `*` with credentials.",
          "Understand preflight (OPTIONS); don't reflect arbitrary Origin.",
          "CORS is not authorization."],
         ["Reflecting Origin with credentials = any site can call your API.",
          "Treating CORS as a security boundary."]),
        ("OAuth2 & OIDC", "oauth", "Integrate OAuth2/OpenID Connect correctly.",
         ["Use auth code flow + PKCE for apps; validate state; verify tokens (sig/aud/exp/iss).",
          "Store tokens safely; refresh correctly; scope minimally.",
          "Never put secrets in a public client."],
         ["Implicit flow / tokens in URLs leak.", "Skipping token validation."]),
        ("Rate limiting", "rate-limiting", "Protect endpoints with correct rate limiting.",
         ["Choose a key (user/IP/API-key) and algorithm (token bucket/sliding window).",
          "Return 429 with Retry-After; limit per-endpoint by cost.",
          "Enforce server-side, distributed if multi-instance."],
         ["Per-instance limits don't hold behind a load balancer.",
          "Limiting by IP only punishes shared NATs."]),
        ("File uploads", "uploads", "Accept file uploads without opening a hole.",
         ["Validate type by content not extension; cap size; store outside the webroot.",
          "Randomize stored names; never execute uploads; scan if serving to others.",
          "Stream large files; set timeouts."],
         ["Trusting the extension/MIME from the client.",
          "Serving uploads from a path that can execute them."]),
        ("Web accessibility", "accessibility", "Build UI usable by everyone (a11y).",
         ["Semantic HTML; label controls; keyboard operable; visible focus.",
          "Sufficient color contrast; alt text; ARIA only when semantics fall short.",
          "Test with a screen reader and keyboard-only."],
         ["Div-soup with click handlers isn't keyboard/AT accessible.",
          "ARIA misused breaks more than it fixes."]),
        ("Responsive CSS", "css", "Build layouts that work at any width.",
         ["Mobile-first; flexbox/grid over floats; relative units; fluid images.",
          "Breakpoints by content, not devices; test at phone width with a side gutter.",
          "Avoid horizontal scroll."],
         ["Fixed pixel widths break on small screens.",
          "Desktop-only testing."]),
    ]
    for name, t, desc, steps, pit in web_topics:
        S(we, name, desc, [t, "web"], f"Working with {name.lower()}.", steps, pit)

    # ── systems / CLI ──
    sy = "systems"
    sys_topics = [
        ("CLI design", "cli", "Design command-line tools people can use.",
         ["Sensible defaults; --help that teaches; consistent flags; readable + machine output.",
          "Exit non-zero on failure; errors to stderr; respect pipes and NO_COLOR.",
          "Confirm destructive actions; support --dry-run."],
         ["Exiting 0 on failure breaks scripts.", "Chatty stdout that can't be piped."]),
        ("Regular expressions", "regex", "Write correct, safe regexes.",
         ["Anchor and be specific; prefer explicit character classes; test against edge cases.",
          "Watch catastrophic backtracking (nested quantifiers); use non-greedy carefully.",
          "For structured formats, prefer a real parser over a mega-regex."],
         ["ReDoS from `(a+)+`-style patterns on hostile input.",
          "Parsing HTML/recursive formats with regex."]),
        ("Subprocess handling", "subprocess", "Run child processes safely and robustly.",
         ["Pass argv arrays, never shell strings with input; set timeouts.",
          "Capture stdout/stderr; check return codes; kill on timeout (and the process group).",
          "Stream output for long runs; avoid deadlocks on full pipes."],
         ["shell=True with input = command injection.",
          "Not reading pipes → child blocks on a full buffer."]),
        ("Signal handling", "signals", "Handle process signals for clean shutdown.",
         ["Trap SIGTERM/SIGINT; flush and clean up; exit promptly.",
          "Make handlers minimal and reentrancy-safe; propagate to children.",
          "Support graceful drain before exit."],
         ["Ignoring SIGTERM → hard kills lose in-flight work.",
          "Heavy work inside a signal handler."]),
        ("Configuration & env", "config", "Manage configuration cleanly across environments.",
         ["Layer: defaults < file < env < flags; validate on load; fail fast on bad config.",
          "Secrets from env/manager, not the config file in git.",
          "Document every setting; sane defaults."],
         ["Secrets committed in config files.",
          "Silent fallback on misconfig hides problems."]),
        ("File I/O safely", "file-io", "Read/write files without corruption or leaks.",
         ["Use context managers; explicit encodings; handle missing/locked files.",
          "Atomic writes (temp + rename) for durability; avoid partial writes.",
          "Stream large files; clean up temp files."],
         ["Non-atomic writes corrupt on crash.",
          "Leaking file handles; wrong/implicit encoding."]),
    ]
    for name, t, desc, steps, pit in sys_topics:
        S(sy, name, desc, [t, "systems"], f"Working with {name.lower()}.", steps, pit)

    # ── networking ──
    ne = "networking"
    net_topics = [
        ("TCP sockets", "sockets", "Write correct TCP socket code.",
         ["Handle partial reads/writes (loop until done); set timeouts; framing for messages.",
          "Clean shutdown/close; handle RST/EOF; back-pressure on slow peers.",
          "Non-blocking or threads for many connections."],
         ["Assuming one recv == one message (TCP is a stream).",
          "No timeout → hung forever on a dead peer."]),
        ("HTTP clients", "http-client", "Make robust outbound HTTP calls.",
         ["Set connect+read timeouts; retry idempotent calls with backoff+jitter.",
          "Handle non-2xx explicitly; stream large bodies; reuse connections.",
          "Validate/limit redirects (SSRF)."],
         ["No timeout → the call hangs your service.",
          "Retrying non-idempotent calls duplicates side effects."]),
        ("Retries & backoff", "retries", "Retry transient failures without making things worse.",
         ["Only retry idempotent/transient failures; exponential backoff WITH jitter; cap attempts.",
          "Respect Retry-After; add a circuit breaker for a failing dependency.",
          "Make the operation idempotent (idempotency keys)."],
         ["Synchronized retries cause a thundering herd.",
          "Retrying a 400/auth error forever."]),
        ("Caching strategies", "caching", "Cache to speed things up without serving stale/wrong data.",
         ["Pick a pattern (cache-aside, write-through); set TTLs; plan invalidation.",
          "Key carefully (include what varies); guard against stampedes (locks/jitter).",
          "Cache only what's safe and hot."],
         ["Invalidation bugs serve stale data.",
          "Caching per-user data under a shared key."]),
        ("Message queues", "queues", "Use a queue/broker for reliable async work.",
         ["At-least-once by default → make consumers idempotent; ack after success.",
          "Dead-letter poison messages; set visibility timeouts; bound concurrency.",
          "Order and exactly-once are hard — design around them."],
         ["Non-idempotent consumers double-process on redelivery.",
          "No DLQ → a poison message blocks the queue."]),
    ]
    for name, t, desc, steps, pit in net_topics:
        S(ne, name, desc, [t, "networking"], f"Working with {name.lower()}.", steps, pit)

    # ── algorithms ──
    al = "algorithms"
    algo_topics = [
        ("Big-O & complexity", "big-o", "Reason about time/space complexity.",
         ["Identify the dominant term; count nested loops and recursion depth.",
          "Know the cost of your data-structure ops; pick structures by access pattern.",
          "Optimize the algorithm before the constant factor."],
         ["Hidden O(n) inside a loop (e.g. `in` on a list) → O(n²).",
          "Optimizing constants while the algorithm is quadratic."]),
        ("Choosing data structures", "data-structures", "Pick the right structure for the job.",
         ["Set/dict for membership/lookup (O(1)); list for order; heap for top-k/priority.",
          "Deque for both-ends; tree/sorted for ordered range queries.",
          "Match the structure to the dominant operation."],
         ["Using a list where a set/dict is needed (quadratic lookups).",
          "Premature exotic structures."]),
        ("Recursion & memoization", "recursion", "Write correct recursion and memoize overlap.",
         ["Define the base case and the shrink step clearly; ensure termination.",
          "Memoize overlapping subproblems; watch recursion depth (convert to iteration if deep).",
          "Reason about the call tree's size."],
         ["Missing/exponential base cases → stack overflow or blowup.",
          "Re-computing the same subproblems (no memoization)."]),
        ("Dynamic programming", "dynamic-programming", "Solve overlapping-subproblem problems with DP.",
         ["Define the state and recurrence; identify overlapping subproblems and optimal substructure.",
          "Top-down (memo) or bottom-up (table); reduce space when possible.",
          "Verify on small cases by hand."],
         ["Wrong state definition → subtle incorrectness.",
          "Forcing DP where greedy/simple works."]),
        ("Sorting & searching", "sorting", "Use sorting and binary search correctly.",
         ["Use the stdlib sort (with a key); sort once to enable binary search / grouping.",
          "Binary search needs a sorted, monotonic space; mind boundaries.",
          "Consider counting/bucket sort for bounded keys."],
         ["Off-by-one and infinite loops in hand-rolled binary search.",
          "Re-sorting repeatedly instead of once."]),
        ("Graph traversal", "graphs", "Traverse and search graphs correctly.",
         ["BFS for shortest unweighted path/levels; DFS for reachability/topo/cycles.",
          "Track visited to avoid infinite loops; Dijkstra/A* for weighted shortest path.",
          "Pick the representation (adjacency list vs matrix) by density."],
         ["No visited set → infinite loops on cycles.",
          "BFS/DFS where a weighted algorithm is needed."]),
        ("String algorithms", "strings", "Handle string processing efficiently and correctly.",
         ["Know when to use hashing, two-pointers, sliding windows, or a trie.",
          "Mind Unicode (code points vs bytes vs graphemes); normalize when comparing.",
          "Avoid quadratic concatenation in loops (use a builder/join)."],
         ["Byte vs character confusion with Unicode.",
          "O(n²) string building in a loop."]),
    ]
    for name, t, desc, steps, pit in algo_topics:
        S(al, name, desc, [t, "algorithms"], f"Working on {name.lower()}.", steps, pit)

    # ── architecture & patterns ──
    ar = "architecture"
    arch_topics = [
        ("SOLID principles", "solid", "Apply SOLID to keep code changeable.",
         ["Single responsibility per unit; depend on abstractions; keep interfaces small.",
          "Open for extension, closed for modification where change is likely.",
          "Apply judgment — principles serve maintainability, not the reverse."],
         ["Over-abstracting simple code in SOLID's name.",
          "God classes doing everything."]),
        ("Dependency injection", "dependency-injection", "Invert dependencies for testability.",
         ["Pass collaborators in (constructor/args) rather than constructing them inside.",
          "Depend on interfaces; wire concrete types at the edge (composition root).",
          "This makes units testable with fakes."],
         ["A heavyweight DI framework where plain params suffice.",
          "Hidden global singletons defeating the point."]),
        ("Design patterns", "design-patterns", "Use classic patterns where they fit — not everywhere.",
         ["Recognize the problem each pattern solves (strategy, factory, observer, adapter).",
          "Apply the simplest thing that works; a pattern is a means, not a goal.",
          "Name things after intent."],
         ["Pattern-itis: forcing patterns onto simple problems.",
          "Singletons as global mutable state."]),
        ("Microservices vs monolith", "microservices", "Choose and structure service boundaries.",
         ["Start with a well-structured monolith; split only for real scaling/team boundaries.",
          "Services own their data; communicate via clear contracts; design for partial failure.",
          "Weigh the operational cost of distribution."],
         ["Premature microservices multiply complexity.",
          "Shared databases coupling 'independent' services."]),
        ("Event-driven architecture", "event-driven", "Design around events and async messaging.",
         ["Model domain events; publish/subscribe with a broker; consumers idempotent.",
          "Handle ordering, duplicates, and replay; version event schemas.",
          "Trace flows across async hops."],
         ["Hidden coupling via event shapes.",
          "No idempotency → duplicate side effects."]),
        ("Caching layers", "cache-layers", "Place caches deliberately across a system.",
         ["Cache at the right layer (CDN, app, DB) for the access pattern; set TTL + invalidation.",
          "Avoid stampedes; keep caches consistent with the source of truth.",
          "Measure hit rate; cache the hot, not everything."],
         ["Multiple uncoordinated caches serving conflicting data.",
          "Caching correctness-critical data without invalidation."]),
    ]
    for name, t, desc, steps, pit in arch_topics:
        S(ar, name, desc, [t, "architecture"], f"Deciding on {name.lower()}.", steps, pit)

    # ── game dev (the operator builds games) ──
    ga = "gamedev"
    game_topics = [
        ("Game loop", "game-loop", "Structure a correct, smooth game loop.",
         ["Separate update (fixed timestep) from render; use delta time for movement.",
          "Cap/decouple frame rate; accumulate time for physics stability.",
          "Handle input, update, render, repeat — keep it deterministic where possible."],
         ["Tying movement to frame rate → speed varies by machine.",
          "Physics in a variable timestep gets unstable."]),
        ("Canvas rendering", "canvas", "Render efficiently on HTML5 canvas.",
         ["Batch draws; minimize state changes; only redraw what changed when possible.",
          "Use requestAnimationFrame; offscreen canvas for static layers; sprite atlases.",
          "Clear/compose deliberately."],
         ["Redrawing everything every frame when little changed.",
          "Per-frame allocations causing GC stutter."]),
        ("Collision detection", "collision", "Detect collisions correctly and cheaply.",
         ["Broad phase (grid/quadtree) then narrow phase (AABB/circle/SAT).",
          "Use swept tests for fast objects to avoid tunneling.",
          "Resolve overlaps stably."],
         ["Checking every pair (O(n²)) without a broad phase.",
          "Tunneling: fast objects passing through thin walls."]),
        ("Sprite animation", "animation", "Animate sprites smoothly.",
         ["Frame-based animation driven by delta time; sprite sheets; state machines for animations.",
          "Decouple animation speed from frame rate; loop/hold correctly.",
          "Pool sprites to avoid churn."],
         ["Animation speed tied to frame rate.",
          "Recreating sprite objects every frame."]),
        ("Game state management", "game-state", "Manage screens and state cleanly.",
         ["A state/scene stack (menu, play, pause, game-over); clear enter/exit hooks.",
          "Keep game state separate from rendering; make it serializable for save/load.",
          "Central update dispatch per state."],
         ["Global tangled state across screens.",
          "Logic and rendering intertwined."]),
        ("Multiplayer netcode", "netcode", "Build responsive, cheat-resistant multiplayer.",
         ["Server-authoritative state; clients send inputs, not positions.",
          "Client-side prediction + reconciliation; interpolate remote entities.",
          "Handle latency/loss; never trust the client."],
         ["Trusting client-reported state → trivial cheating.",
          "No interpolation → jittery remote players."]),
    ]
    for name, t, desc, steps, pit in game_topics:
        S(ga, name, desc, [t, "gamedev"], f"Working on {name.lower()}.", steps, pit)

    # ── security, second wave ──
    sw = "security"
    sec2 = [
        ("web", "Path traversal", ["path-traversal", "lfi", "web"],
         "A file path built from user input.",
         ["Try `../` sequences (and encoded `%2e%2e%2f`, double-encoding) to escape the intended dir.",
          "Reach sensitive files (/etc/passwd, app config, source).",
          "FIX: resolve the path and confirm it stays under the allowed root; allow-list names; never concatenate raw input."],
         ["Blacklisting `../` misses encodings; canonicalize then check the prefix.",
          "Symlinks can escape a naive prefix check."]),
        ("web", "Open redirect", ["open-redirect", "web"],
         "A redirect target taken from user input (?next=, ?url=).",
         ["Supply an external URL and see if the app redirects off-site.",
          "Try `//evil.com`, `https:evil.com`, and encoded variants.",
          "FIX: allow-list redirect targets or only permit relative paths."],
         ["`//host` is protocol-relative and escapes naive checks.",
          "Open redirects enable phishing and OAuth token theft."]),
        ("web", "Clickjacking", ["clickjacking", "web"],
         "A sensitive UI that can be framed by another site.",
         ["Check for X-Frame-Options / CSP frame-ancestors; try framing the page.",
          "FIX: set `frame-ancestors 'none'` (or specific origins) and X-Frame-Options: DENY."],
         ["Only X-Frame-Options without CSP misses some browsers.",
          "Framebusting JS is bypassable."]),
        ("web", "Subdomain takeover", ["subdomain-takeover", "recon", "cloud"],
         "Dangling DNS records pointing at unclaimed services.",
         ["Enumerate subdomains; find CNAMEs to third-party services that return 'not found'/unclaimed.",
          "Confirm you can claim the resource; report/fix by removing the dangling record.",
          "FIX: remove stale DNS; decommission DNS with the service."],
         ["Dangling records to deprovisioned buckets/apps are claimable.",
          "Fixing the service but leaving the DNS record."]),
        ("web", "Race conditions (TOCTOU)", ["race-condition", "toctou", "web"],
         "A check and a use separated in time on shared state (balances, coupons, limits).",
         ["Send many concurrent requests to the state-changing endpoint (e.g. redeem once → redeem many).",
          "Look for limit bypasses from parallelism.",
          "FIX: atomic operations / DB constraints / locks; enforce the invariant in one transaction."],
         ["Application-level checks don't hold under concurrency.",
          "Idempotency keys and unique constraints are the fix, not more checks."]),
        ("recon", "DNS reconnaissance", ["dns", "recon"],
         "Mapping a target's DNS footprint (authorized).",
         ["Enumerate records (A/AAAA/MX/TXT/NS/CNAME); brute subdomains; check zone transfer (AXFR).",
          "Use cert transparency (crt.sh) and passive DNS for more names.",
          "Map the results into the attack surface."],
         ["Zone transfer is rarely open but a jackpot when it is.",
          "Wildcard DNS causes false-positive subdomains."]),
        ("appsec", "SAST review", ["sast", "static-analysis", "appsec"],
         "Static review of a codebase for vulns.",
         ["Run semgrep/bandit with security rulesets; triage by reachability.",
          "Manually audit auth, input handling, crypto, and dangerous sinks the scanner flags.",
          "Confirm each finding in context; drop false positives; fix real ones."],
         ["Treating every scanner hit as a real bug.",
          "Trusting the scanner to find logic/authz flaws (it won't)."]),
        ("appsec", "Container security", ["containers", "docker", "security"],
         "Hardening a containerized workload.",
         ["Minimal base, non-root, read-only FS, dropped caps, no privileged mode.",
          "Scan images for CVEs; keep secrets out of layers; sign/verify images.",
          "Least-privilege at runtime (seccomp/apparmor); network policies."],
         ["Root + privileged containers = easy host compromise.",
          "Secrets baked into image layers."]),
        ("cloud", "Cloud metadata & SSRF", ["cloud", "ssrf", "metadata"],
         "SSRF against cloud metadata endpoints.",
         ["From an SSRF, hit 169.254.169.254 for instance credentials/role tokens.",
          "Use the creds to enumerate cloud permissions (authorized).",
          "FIX: enforce IMDSv2, block metadata from app egress, scope IAM roles tightly."],
         ["IMDSv1 hands out creds to any SSRF.",
          "Over-broad instance roles turn one SSRF into full account access."]),
        ("blue", "Incident response basics", ["dfir", "incident-response", "blue-team"],
         "Responding to a suspected compromise.",
         ["Contain first (isolate), preserve evidence (don't wipe), then investigate.",
          "Build a timeline from logs; scope the blast radius; identify entry + persistence.",
          "Eradicate, recover, and write the postmortem with concrete fixes."],
         ["Rebooting/reimaging destroys volatile evidence.",
          "Declaring 'clean' without finding the entry point."]),
        ("exploit", "Active Directory attacks", ["active-directory", "windows", "privesc"],
         "Assessing an AD environment (authorized).",
         ["Enumerate (BloodHound) for attack paths; kerberoast service accounts; check ACL abuse.",
          "Look for AS-REP roasting, weak delegation, and credential reuse to reach DA.",
          "FIX: tier admin, strong service-account passwords, least privilege, monitoring."],
         ["Kerberoastable accounts with weak passwords = domain foothold.",
          "Flat admin models let one host compromise the domain."]),
        ("exploit", "Pivoting & tunneling", ["pivoting", "post-exploitation", "network"],
         "Reaching internal networks through a foothold (authorized).",
         ["Map reachable internal hosts from the foothold; set up port forwards / SOCKS (ssh -D, chisel).",
          "Route tools through the tunnel; stay within scope.",
          "Document the path for the report."],
         ["Pivoting outside the authorized scope.",
          "Noisy scanning through the tunnel tips off defenders."]),
        ("crypto", "TLS configuration", ["tls", "crypto", "hardening"],
         "Configuring or reviewing TLS for a service.",
         ["Modern protocols only (TLS 1.2/1.3); strong cipher suites; disable renegotiation/compression.",
          "Valid cert chain; HSTS; OCSP stapling; test with an SSL scanner.",
          "Rotate keys; protect private keys."],
         ["Old protocols/ciphers (SSLv3, RC4) break confidentiality.",
          "Self-signed/expired certs train users to ignore warnings."]),
        ("appsec", "Input validation", ["validation", "appsec"],
         "Any boundary receiving external data.",
         ["Validate type, range, length, and format at the trust boundary; allow-list where possible.",
          "Reject rather than sanitize when you can; canonicalize before checks.",
          "Validate on the server even if the client does too."],
         ["Client-side validation is a UX feature, not a security control.",
          "Blocklists miss cases allow-lists wouldn't."]),
        ("reversing", "Static binary analysis", ["reversing", "binary"],
         "Understanding an unknown binary (authorized).",
         ["Triage: file type, strings, imports, packing; then disassemble (Ghidra/radare2).",
          "Map the control flow; name functions; find the interesting logic (crypto, network, checks).",
          "Extract the primitive you need (keys, protocol, algorithm)."],
         ["Packed/obfuscated binaries need unpacking first.",
          "Getting lost — anchor on strings/imports/syscalls."]),
    ]
    for cat, name, tags, when, steps, pit in sec2:
        S(f"security/{cat}", name,
          f"{name}: find, exploit (authorized), and fix.", tags, when, steps, pit)

    # ── AI agents & LLM apps (the operator builds AI tools) ──
    ai = "ai-agents"
    ai_topics = [
        ("Agent loop design", "agent-loop", "Structure a reliable model→tools→observe loop.",
         ["Stream the model, parse tool calls, execute, feed results back, repeat until done.",
          "Bound the loop (max steps); detect and break empty/degraded replies.",
          "Keep the system prompt authoritative; make tools return actionable errors."],
         ["No step ceiling → runaway loops.",
          "Silent empty replies stalling the loop without a retry/backstop."]),
        ("Native tool calling", "tool-calling", "Wire OpenAI-style structured function calling.",
         ["Send a JSON-schema `tools` array; read structured tool_calls; round-trip role:tool results by id.",
          "Keep the whole history in one channel (structured) so the model gets no mixed signal.",
          "Fall back to a text protocol if the provider rejects the tools field."],
         ["Mixing structured + text tool history confuses the model.",
          "Losing the tool_call_id linkage breaks the round-trip."]),
        ("Structured LLM output", "structured-output", "Get machine-parseable output from an LLM.",
         ["Specify a strict schema; use JSON mode/function calling; VALIDATE the output.",
          "Handle parse failures with a repair prompt or retry; never trust format blindly.",
          "Give a concrete example of the exact shape."],
         ["Assuming valid JSON without validation.",
          "No repair path when the model drifts from the schema."]),
        ("Context window management", "context", "Keep the model's context focused and within budget.",
         ["Include only what the task needs; summarize or drop old turns; pin the system prompt.",
          "Compress bulky tool outputs; track token budget; retrieve on demand rather than stuffing.",
          "Order matters — put the most relevant last."],
         ["Stuffing irrelevant context degrades quality and costs tokens.",
          "Silently truncating the system prompt."]),
        ("Prompt injection defense", "prompt-injection", "Defend an LLM app against injected instructions.",
         ["Treat all retrieved/tool/user content as DATA, not instructions; fence it clearly.",
          "Keep the trusted system prompt separate and authoritative; least-privilege tools.",
          "Gate dangerous tool actions with confirmation; sanitize/label untrusted text."],
         ["Concatenating web/RAG content into the instruction channel.",
          "Giving the agent unconstrained powerful tools."]),
        ("LLM evaluation", "evals", "Measure whether an LLM feature actually works.",
         ["Build a labeled eval set of real cases; define pass criteria; run on every change.",
          "Test edge cases and adversarial inputs; track regressions over time.",
          "Prefer automatic checks; use human review for the subjective."],
         ["Vibe-checking a few prompts and shipping.",
          "No regression set → silent quality drift."]),
        ("Streaming responses", "streaming", "Stream model output to the UI correctly.",
         ["Parse SSE/deltas incrementally; flush tokens to the UI as they arrive.",
          "Accumulate tool-call fragments by index/id; handle [DONE] and errors mid-stream.",
          "Don't block the UI thread; handle cancellation."],
         ["Buffering the whole response defeats streaming.",
          "Mishandling partial tool-call chunks."]),
        ("Token budgeting & cost", "cost", "Control LLM token usage and cost.",
         ["Measure prompt+completion tokens per call; trim context; cap max_tokens.",
          "Cache repeated context; pick the cheapest model that passes evals.",
          "Batch and dedupe requests."],
         ["Re-sending huge unchanging context every turn.",
          "Using a flagship model where a small one passes."]),
        ("Agent memory", "memory", "Give an agent durable, relevant memory.",
         ["Separate short-term (conversation) from long-term (facts, retrieved on need).",
          "Store durable facts, not transient chatter; dedupe; retrieve by relevance.",
          "Bound the memory scan; keep it correct and private."],
         ["Remembering everything → noise and privacy risk.",
          "Full-scan recall that grows unbounded per turn."]),
        ("Provider fallback & retries", "fallback", "Keep an LLM app up when a provider fails.",
         ["Timeout + retry transient errors with backoff; fall back to another provider/model.",
          "Surface auth/quota errors clearly; degrade gracefully.",
          "Make calls idempotent where retried."],
         ["No timeout → the app hangs on a stalled provider.",
          "Retrying non-retryable (400/auth) errors."]),
    ]
    for name, t, desc, steps, pit in ai_topics:
        S(ai, name, desc, [t, "llm", "ai"], f"Building {name.lower()} in an LLM app.", steps, pit)

    # ── automation ──
    au = "automation"
    auto_topics = [
        ("Web scraping", "scraping", "Scrape web data reliably and politely.",
         ["Respect robots/ToS and rate limits; identify yourself; cache responses.",
          "Prefer APIs; parse HTML with a real parser; handle pagination and failures.",
          "Be resilient to layout changes; back off on errors."],
         ["Hammering a site gets you blocked/banned.",
          "Brittle selectors that break on any redesign."]),
        ("Browser automation", "browser", "Drive a headless browser for tasks/tests.",
         ["Use Playwright/Selenium; wait on conditions not sleeps; stable selectors (roles/test-ids).",
          "Handle dialogs, downloads, and auth; run headless in CI.",
          "Clean up contexts; isolate state per run."],
         ["Fixed sleeps cause flakiness.",
          "Leaking browser contexts/processes."]),
        ("API integration", "api-integration", "Integrate a third-party API robustly.",
         ["Read the docs and rate limits; auth securely; handle pagination and partial data.",
          "Timeouts, retries with backoff, and idempotency; validate responses.",
          "Wrap it behind a small client you can test/mock."],
         ["No timeout/retry → your app inherits their outages.",
          "Trusting response shapes without validation."]),
        ("Scheduled jobs", "cron", "Run recurring jobs reliably.",
         ["Make jobs idempotent; handle overlap (locking); log start/end/outcome.",
          "Alert on failure and on missed runs; keep runtimes bounded.",
          "Store schedules in code/config, not just crontab."],
         ["Overlapping runs corrupting shared state.",
          "Silent failures nobody notices for weeks."]),
        ("Webhooks", "webhooks", "Send and receive webhooks safely.",
         ["Verify signatures on inbound; respond fast then process async; dedupe by event id.",
          "Retry outbound with backoff; make handlers idempotent.",
          "Validate payloads; guard against SSRF on any URL you call."],
         ["Not verifying signatures → spoofed events.",
          "Slow synchronous handlers timing out the sender."]),
        ("Notifications", "notifications", "Deliver notifications without spamming.",
         ["Debounce/batch; respect user preferences and quiet hours; make them actionable.",
          "Handle delivery failures/retries; don't leak sensitive data in them.",
          "Rate-limit per user."],
         ["Alert fatigue from too many low-value pings.",
          "Leaking secrets/PII in notification bodies."]),
    ]
    for name, t, desc, steps, pit in auto_topics:
        S(au, name, desc, [t, "automation"], f"Working on {name.lower()}.", steps, pit)

    # ── advanced git ──
    gi = "git"
    git_topics = [
        ("Interactive rebase", "rebase", "Clean up history with interactive rebase.",
         ["`git rebase -i` to squash/reorder/edit/drop commits before sharing.",
          "Rewrite messages; split commits; keep each commit buildable.",
          "Only rewrite UNPUSHED/local history."],
         ["Rebasing shared branches rewrites others' history.",
          "Force-push clobbering teammates (use --force-with-lease)."]),
        ("git bisect", "bisect", "Find the commit that introduced a bug fast.",
         ["`git bisect start`; mark good/bad; test each midpoint (or `run` a script).",
          "Binary-search the history to the exact bad commit.",
          "Reset when done; add a regression test."],
         ["A flaky test misleads bisect.",
          "Forgetting `git bisect reset` afterward."]),
        ("git hooks", "hooks", "Automate checks with git hooks.",
         ["pre-commit for lint/format/secret-scan; commit-msg for message rules.",
          "Keep hooks fast; share them (pre-commit framework) so the team gets them.",
          "Server-side hooks for enforced policy."],
         ["Slow hooks make people `--no-verify`.",
          "Local-only hooks not shared with the team."]),
        ("git submodules & subtrees", "submodules", "Manage nested repos correctly.",
         ["Understand submodule pinning (a commit, not a branch); update deliberately.",
          "Clone with `--recursive`; document the workflow; consider subtree as an alternative.",
          "Keep the pointer commit in sync."],
         ["Forgetting to init/update submodules → empty dirs.",
          "Detached-HEAD confusion inside submodules."]),
        ("Cherry-pick & revert", "cherry-pick", "Move or undo specific commits safely.",
         ["Cherry-pick to port a fix to another branch; revert to undo on shared history.",
          "Resolve conflicts carefully; keep the intent.",
          "Prefer revert over reset on anything pushed."],
         ["Reset --hard on shared branches loses work.",
          "Cherry-picking creating duplicate commits/conflicts on later merge."]),
    ]
    for name, t, desc, steps, pit in git_topics:
        S(gi, name, desc, [t, "git", "vcs"], f"Using {name.lower()}.", steps, pit)

    # ── web extras ──
    we = "web"
    web2 = [
        ("Progressive web apps", "pwa", "Make a web app installable and offline-capable.",
         ["Add a manifest + service worker; cache the shell; handle offline gracefully.",
          "Update strategy for the SW; HTTPS required; test install/offline.",
          "Don't cache what must be fresh."],
         ["Aggressive SW caching serving stale app forever.",
          "No update path for a deployed service worker."]),
        ("SEO fundamentals", "seo", "Make pages discoverable and rankable.",
         ["Semantic HTML, unique titles/meta, clean URLs, sitemap, structured data.",
          "Fast load and mobile-friendly; server-render or pre-render for crawlers.",
          "Canonical URLs; avoid duplicate content."],
         ["Client-only rendering that crawlers can't read.",
          "Duplicate content without canonicals."]),
        ("Forms & validation", "forms", "Build forms that validate and fail gracefully.",
         ["Validate on the client for UX AND on the server for safety; clear inline errors.",
          "Accessible labels/errors; preserve input on failure; protect against CSRF.",
          "Debounce async validation."],
         ["Client-only validation is bypassable.",
          "Losing the user's input on a failed submit."]),
        ("Internationalization", "i18n", "Support multiple languages and locales.",
         ["Externalize strings; format dates/numbers/currency per locale; handle plurals/RTL.",
          "Don't concatenate translated fragments; give translators context.",
          "Test with long strings and RTL."],
         ["String concatenation breaks grammar across languages.",
          "Hardcoded formats/assumptions about text direction."]),
        ("Image & asset optimization", "assets", "Ship fast pages by optimizing assets.",
         ["Right formats (WebP/AVIF); responsive sizes; lazy-load below the fold; compress.",
          "Cache-bust with hashed names; preload critical assets; minify JS/CSS.",
          "Measure with a performance budget."],
         ["Shipping huge unoptimized images.",
          "Blocking render on non-critical assets."]),
    ]
    for name, t, desc, steps, pit in web2:
        S(we, name, desc, [t, "web"], f"Working on {name.lower()}.", steps, pit)

    # ── devops extras ──
    do = "devops"
    do2 = [
        ("Zero-downtime deploys", "zero-downtime", "Deploy without dropping requests.",
         ["Rolling/blue-green with health checks; drain connections before stopping old.",
          "Backward-compatible schema/API changes (expand/contract); readiness gates traffic.",
          "Automate rollback on failed health."],
         ["Breaking schema changes during a rolling deploy.",
          "No readiness check → traffic to a cold instance."]),
        ("Feature flags", "feature-flags", "Ship safely behind flags.",
         ["Decouple deploy from release; flag risky changes; target subsets; kill-switch.",
          "Keep flags short-lived; clean up dead flags; test both states.",
          "Default safe."],
         ["Flag debt: stale flags no one dares remove.",
          "Untested off-path of a flag."]),
        ("Health checks", "health-checks", "Expose liveness/readiness correctly.",
         ["Liveness = am I alive (restart if not); readiness = can I serve (gate traffic).",
          "Check real dependencies in readiness, not liveness; keep them cheap.",
          "Fail readiness during startup/shutdown."],
         ["Liveness that checks deps causes restart storms.",
          "Readiness always-true → traffic to a broken instance."]),
        ("Backup & restore", "backup", "Have backups you can actually restore.",
         ["Automate backups; store off-site/encrypted; set retention.",
          "TEST restores regularly — an untested backup is a hope, not a plan.",
          "Document RTO/RPO."],
         ["Never testing a restore until you need it.",
          "Backups next to (and deletable with) the data."]),
        ("Log aggregation", "log-aggregation", "Centralize logs for search and alerting.",
         ["Ship structured logs off-host to a central store; index by service/request id.",
          "Retention + PII scrubbing; correlate across services; alert on patterns.",
          "Keep volume/cost in check with levels/sampling."],
         ["Logs only on the host (gone when it dies).",
          "Logging PII/secrets into the aggregator."]),
    ]
    for name, t, desc, steps, pit in do2:
        S(do, name, desc, [t, "devops", "sre"], f"Working on {name.lower()}.", steps, pit)

    # ── testing extras ──
    te = "testing"
    te2 = [
        ("Contract testing", "contract", "Verify services agree on their interface.",
         ["Define the contract; consumer-driven tests; verify the provider against it in CI.",
          "Version contracts; catch breaking changes before deploy.",
          "Test both sides."],
         ["Integration drift caught only in production.",
          "Contracts that aren't verified in CI."]),
        ("Test fixtures & data", "fixtures", "Manage test data without coupling tests.",
         ["Build fixtures with factories/builders; minimal per-test data; isolate state.",
          "Deterministic seeds; clean up; avoid shared mutable fixtures.",
          "Name data by intent."],
         ["Giant shared fixtures coupling unrelated tests.",
          "Order-dependent tests from leaked state."]),
        ("Flaky test triage", "flaky", "Find and fix nondeterministic tests.",
         ["Reproduce by re-running/seeding; find the source (time, order, network, concurrency).",
          "Fix the root cause (fake time/network, isolate state); quarantine only temporarily.",
          "Track flake rate."],
         ["Retrying flakes forever instead of fixing them.",
          "Ignoring flakes until the suite is untrusted."]),
    ]
    for name, t, desc, steps, pit in te2:
        S(te, name, desc, [t, "testing"], f"Working on {name.lower()}.", steps, pit)

    # ── performance ──
    pe = "performance"
    pe_topics = [
        ("Profiling workflow", "profiling", "Find the real bottleneck before optimizing.",
         ["Reproduce a representative workload; profile (CPU/alloc/wall); read the hot path.",
          "Fix the biggest cost first; re-profile to confirm; stop when good enough.",
          "Optimize algorithm before constants."],
         ["Optimizing by guess/intuition.",
          "Micro-optimizing cold code."]),
        ("Memory leak hunting", "memory-leaks", "Track down growing memory use.",
         ["Confirm growth over time; snapshot/diff the heap; find retained references.",
          "Common causes: unbounded caches/lists, listeners not removed, closures capturing.",
          "Fix and verify the curve flattens."],
         ["Unbounded caches masquerading as leaks.",
          "Event listeners/subscriptions never removed."]),
        ("Lazy loading", "lazy-loading", "Defer work until it's needed.",
         ["Load code/data/images on demand; split bundles; paginate; virtualize long lists.",
          "Prefetch likely-next; show placeholders.",
          "Measure the win."],
         ["Lazy-loading above-the-fold content hurts UX.",
          "Waterfalls from serial lazy loads."]),
        ("Request batching", "batching", "Reduce round-trips by batching.",
         ["Batch N small calls into one (dataloader pattern); debounce bursts.",
          "Bound batch size and latency; handle partial failures.",
          "Cache within a request."],
         ["Batching that adds unacceptable latency.",
          "One failure failing the whole batch when it needn't."]),
        ("Connection pooling", "pooling", "Reuse expensive connections correctly.",
         ["Pool DB/HTTP connections; size the pool to the workload and limits.",
          "Set acquire timeouts; validate/health-check idle conns; close on shutdown.",
          "Avoid leaks — always return connections."],
         ["Leaked connections exhausting the pool.",
          "Oversized pools overwhelming the DB."]),
        ("Pagination at scale", "pagination", "Page large result sets efficiently.",
         ["Prefer keyset/cursor pagination over OFFSET for large tables.",
          "Index the sort key; return a stable cursor; cap page size.",
          "Avoid COUNT(*) on huge tables per page."],
         ["OFFSET pagination degrades linearly on deep pages.",
          "Unstable ordering skips/repeats rows."]),
    ]
    for name, t, desc, steps, pit in pe_topics:
        S(pe, name, desc, [t, "performance"], f"Working on {name.lower()}.", steps, pit)

    # ── security, third wave (web logic & protocol) ──
    sw = "security/web"
    sec3 = [
        ("Mass assignment", ["mass-assignment", "web", "api"],
         "An endpoint binding request fields straight onto a model.",
         ["Send extra fields (role, is_admin, verified) and see if they persist.",
          "FIX: bind an explicit allow-list of fields; never trust the whole body."],
         ["Auto-binding the request body onto the model object.",
          "Hidden fields aren't protection."]),
        ("Business logic flaws", ["business-logic", "web"],
         "Abusing intended functionality in unintended ways.",
         ["Map the workflow; test negative/zero/huge quantities, skipped steps, replayed actions.",
          "Look for price/discount manipulation, step-skipping, and state confusion.",
          "FIX: enforce invariants server-side at each step."],
         ["Trusting client-driven workflow order.",
          "Scanners don't find these — think like an abuser."]),
        ("HTTP request smuggling", ["request-smuggling", "web"],
         "Front-end and back-end disagree on request boundaries.",
         ["Probe CL.TE / TE.CL discrepancies carefully in an authorized lab.",
          "Detect via timing/differential responses; understand the proxy chain.",
          "FIX: normalize/reject ambiguous length headers; use HTTP/2 end-to-end."],
         ["This can poison other users' requests — test only with authorization.",
          "Ambiguous Content-Length/Transfer-Encoding is the root."]),
        ("Web cache poisoning", ["cache-poisoning", "web"],
         "Getting a harmful response cached and served to others.",
         ["Find unkeyed inputs (headers) that affect the response but aren't in the cache key.",
          "Poison via that input; confirm it's served to others.",
          "FIX: include all response-affecting inputs in the cache key; sanitize."],
         ["Reflecting unkeyed headers into cached responses.",
          "Overly aggressive caching of dynamic content."]),
        ("Host header injection", ["host-header", "web"],
         "The app trusts the Host header for links/logic.",
         ["Change Host/X-Forwarded-Host; check password-reset links, redirects, cache keys.",
          "FIX: use a configured canonical host; validate/allow-list Host; don't build links from it."],
         ["Password-reset poisoning via attacker-controlled Host.",
          "Trusting X-Forwarded-* without a trusted proxy."]),
        ("SSRF-to-RCE chains", ["ssrf", "rce", "web"],
         "Escalating an SSRF into code execution.",
         ["From SSRF reach internal admin panels, unauth'd services, or cloud metadata.",
          "Chain to RCE via an internal vulnerable service or credential theft (authorized).",
          "FIX: the SSRF fixes (allow-list, IP validation, no redirects) plus internal auth."],
         ["Internal services with no auth assume the network is trusted.",
          "One SSRF + IMDSv1 = cloud account compromise."]),
    ]
    for name, tags, when, steps, pit in sec3:
        S(sw, name, f"{name}: find, exploit (authorized), and fix.",
          tags, when, steps, pit)

    # ── a final handful to round out the library ──
    S("security/appsec", "Security headers", "Set the HTTP security headers that matter.",
      ["headers", "hardening", "web"], "Hardening any web response.",
      ["CSP (no unsafe-inline), HSTS, X-Content-Type-Options: nosniff, frame-ancestors, Referrer-Policy.",
       "Set them globally at the edge/middleware; test with a header scanner.",
       "Tune CSP to the app; report-only first, then enforce."],
      ["A CSP with unsafe-inline gives little protection.",
       "Setting headers on some routes but not others."])
    S("practices", "Reading unfamiliar code", "Get productive in a codebase you didn't write.",
      ["onboarding", "reading-code"], "Starting on an unfamiliar project.",
      ["Start at the entry point and the build/test commands; run it first.",
       "Trace one real request/flow end to end; map the module boundaries.",
       "Read tests to learn intended behavior; use grep/symbols to navigate; change something small and run it."],
      ["Reading top-to-bottom instead of following a flow.",
       "Changing things before you can run and test them."])
    S("practices", "Estimating work", "Give honest, useful estimates.",
      ["estimation", "planning"], "Sizing a task before committing.",
      ["Break the work down; estimate the pieces; add explicit unknowns/risk buffer.",
       "Give a range, not a false-precise number; state assumptions.",
       "Re-estimate as you learn; flag slippage early."],
      ["A single number hides the uncertainty.",
       "Estimating the happy path only, ignoring testing/edge cases."])
    S("web", "Session management", "Manage web sessions securely.",
      ["session", "auth", "web"], "Any stateful, authenticated web app.",
      ["Server-side sessions or signed tokens; httpOnly+Secure+SameSite cookies.",
       "Rotate the id on login/privilege change; expire idle + absolute; invalidate on logout.",
       "Bind minimal data; protect against fixation and CSRF."],
      ["Session fixation from not rotating the id at login.",
       "Long-lived sessions with no server-side invalidation."])
    S("systems", "Cross-platform code", "Write code that works across OSes.",
      ["cross-platform", "portability"], "Code that must run on Linux/macOS/Windows.",
      ["Use the stdlib path/OS abstractions (pathlib/os.path); avoid shelling out to OS-specific tools.",
       "Handle path separators, line endings, and case sensitivity; detect the platform when needed.",
       "Test on each target (CI matrix)."],
      ["Hardcoded `/` paths or platform-specific commands.",
       "Assuming a case-sensitive/insensitive filesystem."])
    S("ai-agents", "MCP tool integration", "Integrate Model Context Protocol tools/servers.",
      ["mcp", "tools", "llm"], "Adding external tools to an agent via MCP.",
      ["Speak JSON-RPC over stdio; handshake, list tools, call by name; map results back.",
       "Timeout and clean up child processes; handle a hung server (kill to unblock reads).",
       "Gate tool actions by permission; treat tool output as untrusted data."],
      ["Leaking the subprocess/threads when a handshake fails.",
       "A blocking read with no real timeout hanging the agent."])
    S("data-ml", "Feature engineering", "Build features that help a model without leaking.",
      ["ml", "features"], "Preparing inputs for a model.",
      ["Derive features from domain knowledge; fit transforms on TRAIN only, apply to test.",
       "Handle missing values and scaling consistently; avoid target leakage.",
       "Validate feature distributions train vs serve."],
      ["Fitting scalers/encoders on the whole dataset leaks test info.",
       "Train/serve skew from inconsistent transforms."])
